### ISSUE TITLE
Crunchyroll Addition

### ISSUE THREAD

**Issue by elliotrpage** [theshillito/the-mx-thing#6]
Hello! I'm not in a position to do a PR right now so this is an Issue, Sorry.

Crunchyroll-
As an existing account, I navigated to the Profile page, where they have a Gender field.
The field allows you to either not set a gender ("-") as the field is optional, or select "Other".
I am not sure if "Other" comes under the "Prefer not to say" clause.

Best,
Elliot

**Comment by theshillito** [comment]
Thanks for reporting. "Other" is fine in my book. I'll get to this when I can. Do Crunchyroll require a title at all?

**Comment by elliotrpage** [comment]
No Title required.

They let you add your blood group though!
