### ISSUE TITLE
holidaycottages.co.uk

### ISSUE THREAD

**Issue by elliotrpage** [theshillito/the-mx-thing#7]
Sorry, I'm away from my main PC again, but have an additional data point:

holidaycottages.co.uk:
Requires a Title when making an enquiry or a booking, and is restricted to Mr/Miss/Ms/Mrs/Dr/Prof/Rev. 

Have e-mailed to enquire, no reply as yet

**Comment by elliotrpage** [comment]
Note: field is required, hence how I walked into it.

**Comment by theshillito** [comment]
Thank you Elliot ^_^
